import type { Metadata } from "next";

import "./globals.css";
import StoreProvider from "./StoreProvider";

import {Nunito_Sans} from 'next/font/google'

const nunitoSans = Nunito_Sans({
  weight : ['600','700'],
  style : 'normal',
  subsets : ['latin'],
  display : 'swap'
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={nunitoSans.className}>{children}</body>
      </StoreProvider>
    </html>
  );
}
